// <auto-generated />
using System;
using BudgetApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BudgetApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("BudgetApp.Models.BudgetPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("KorisnikId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UkupanPrihodPlana")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KorisnikId");

                    b.ToTable("BudgetPlan");
                });

            modelBuilder.Entity("BudgetApp.Models.BudgetPlan_Trosak_Kategorija", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BudgetPlanId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("IznosKm")
                        .HasColumnType("TEXT");

                    b.Property<int>("KategorijaTroskaId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ProcenatPlana")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BudgetPlanId");

                    b.HasIndex("KategorijaTroskaId");

                    b.ToTable("BudgetPlanTrosakKategorija");
                });

            modelBuilder.Entity("BudgetApp.Models.KategorijaTroska", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("KategorijaTroska");
                });

            modelBuilder.Entity("BudgetApp.Models.Korisnik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Napravljeno")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Korisnici");
                });

            modelBuilder.Entity("BudgetApp.Models.Prihodi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("TEXT");

                    b.Property<int>("KorisnikId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Napomena")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SigurnostPlateId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TagoviId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Ukupno")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KorisnikId");

                    b.HasIndex("SigurnostPlateId");

                    b.HasIndex("TagoviId");

                    b.ToTable("Prihodi");
                });

            modelBuilder.Entity("BudgetApp.Models.PrioritetTroska", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PrioritetTroska");
                });

            modelBuilder.Entity("BudgetApp.Models.SigurnostPlate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SigurnostPlate");
                });

            modelBuilder.Entity("BudgetApp.Models.Tagovi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tagovi");
                });

            modelBuilder.Entity("BudgetApp.Models.Troskovi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("TEXT");

                    b.Property<int>("KategorijaTroskaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KorisnikId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Napomena")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PrioritetTroskaId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Ukupno")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KategorijaTroskaId");

                    b.HasIndex("KorisnikId");

                    b.HasIndex("PrioritetTroskaId");

                    b.ToTable("Troskovi");
                });

            modelBuilder.Entity("BudgetApp.Models.BudgetPlan", b =>
                {
                    b.HasOne("BudgetApp.Models.Korisnik", "Korisnik")
                        .WithMany("BudgetPlan")
                        .HasForeignKey("KorisnikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Korisnik");
                });

            modelBuilder.Entity("BudgetApp.Models.BudgetPlan_Trosak_Kategorija", b =>
                {
                    b.HasOne("BudgetApp.Models.BudgetPlan", "BudgetPlan")
                        .WithMany("StavkeKategorije")
                        .HasForeignKey("BudgetPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BudgetApp.Models.KategorijaTroska", "KategorijaTroska")
                        .WithMany()
                        .HasForeignKey("KategorijaTroskaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BudgetPlan");

                    b.Navigation("KategorijaTroska");
                });

            modelBuilder.Entity("BudgetApp.Models.Prihodi", b =>
                {
                    b.HasOne("BudgetApp.Models.Korisnik", "Korisnik")
                        .WithMany("Prihodi")
                        .HasForeignKey("KorisnikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BudgetApp.Models.SigurnostPlate", "Sigurnost")
                        .WithMany("Prihodi")
                        .HasForeignKey("SigurnostPlateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BudgetApp.Models.Tagovi", "Tag")
                        .WithMany("Prihodi")
                        .HasForeignKey("TagoviId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Korisnik");

                    b.Navigation("Sigurnost");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("BudgetApp.Models.Troskovi", b =>
                {
                    b.HasOne("BudgetApp.Models.KategorijaTroska", "KategorijaTroska")
                        .WithMany("Troskovi")
                        .HasForeignKey("KategorijaTroskaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BudgetApp.Models.Korisnik", "Korisnik")
                        .WithMany("Troskovi")
                        .HasForeignKey("KorisnikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BudgetApp.Models.PrioritetTroska", "PrioritetTroska")
                        .WithMany("Troskovi")
                        .HasForeignKey("PrioritetTroskaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KategorijaTroska");

                    b.Navigation("Korisnik");

                    b.Navigation("PrioritetTroska");
                });

            modelBuilder.Entity("BudgetApp.Models.BudgetPlan", b =>
                {
                    b.Navigation("StavkeKategorije");
                });

            modelBuilder.Entity("BudgetApp.Models.KategorijaTroska", b =>
                {
                    b.Navigation("Troskovi");
                });

            modelBuilder.Entity("BudgetApp.Models.Korisnik", b =>
                {
                    b.Navigation("BudgetPlan");

                    b.Navigation("Prihodi");

                    b.Navigation("Troskovi");
                });

            modelBuilder.Entity("BudgetApp.Models.PrioritetTroska", b =>
                {
                    b.Navigation("Troskovi");
                });

            modelBuilder.Entity("BudgetApp.Models.SigurnostPlate", b =>
                {
                    b.Navigation("Prihodi");
                });

            modelBuilder.Entity("BudgetApp.Models.Tagovi", b =>
                {
                    b.Navigation("Prihodi");
                });
#pragma warning restore 612, 618
        }
    }
}
